name: e16
channels:
  - defaults
dependencies:
  - python=3.7.3
  - numpy
  - pip
  - matplotlib
  - scipy

# I use opencv version 3.4.2.17 but it's installed using pip
# in my virtual enviroment directory.
# command: 
# pip install opencv-python==3.4.2.17
# pip install opencv-contrib-python==3.4.2.17

# so this .yml only install python, numpy, etc.
